# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary29062002

------WebKitFormBoundary29062002
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary29062002--

###

# @name create-transcription
POST http://localhost:3333/videos/17bc4ccb-aa50-490f-ae34-6285a6fa39ff/transcription
Content-Type: application/json

{
  "prompt": "clean architecture, ddd"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "17bc4ccb-aa50-490f-ae34-6285a6fa39ff",
  "template": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}